project_id = "tecqsudwgiqvwrraxzsk"

[functions.create-user]
verify_jwt = false

[functions.send-reset-password]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.clock-attendance]
verify_jwt = false

